name: Docker build & push, Kubernetes start

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          logout: true

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Docker build & push, kubectl apply
        run: |
          docker build -t ${{ secrets.ACR_URL }}/podtranscription:${{ github.sha }} .
          docker push ${{ secrets.ACR_URL }}/podtranscription:${{ github.sha }}
          sed -i'' -e 's/ACR_URL/${{ secrets.ACR_URL }}/g' -e 's/AKS_URL/${{ secrets.AKS_URL }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' k8s.yaml
          kubectl apply -f k8s.yaml
