name: Docker Build and Push Kubernetes deploy

on:
  push:
    branches:  
    - main
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        registry:  ${{ secrets.ACR_URL }}
        username:  ${{ secrets.ACR_USERNAME }}
        password:  ${{ secrets.ACR_PASSWORD }}
        
    - name: Kubernetes Set Context
      uses: Azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
  
    
    - name: Build the Docker image
      run: 
        docker build . --tag ${{ secrets.ACR_URL }}//podtranscription:${{ github.sha }} .
        docker push ${{ secrets.ACR_URL }}//podtranscription:${{ github.sha }}
        sed -i'' -e 's/ACR_URL/${{ secrets.ACR_URL }}/g' -e 's/AKS_URL/${{ secrets.AKS_URL }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' kubernetes.yaml 
        kubectl apply -f kubernetes.yaml
